RGRIDT-1051: Fixing issue when adding rows and removing wrong use of API
OutSystems/outsystems-datagrid-reactive pull request #154
Opened 2021-11-02 11:48 UTC by glundgren93

This PR is for a bug fix reported on the forum.

[Sample page](url)

### What was happening
* Whenever we tried to add rows on the grid with dependent dropdowns, an error was thrown. This was happening because the grid behaved as if the filters were applied.

### What was done
* Added an extra validation on the filter test.
* Removed wrong use of GridAPI on wijmoProvider.

### Test Steps
1. Open the context menu and add row.
2. Row should be added.

### Checklist
* [x] tested locally
* [x] documented the code
* [x] clean all warnings and errors of eslint

2021-11-02 12:03 UTC, tmbp95 approved these changes

2021-11-02 12:33 UTC, rugoncalves requested changes
Well done! Liked specially the fix that you did to remove the calls do the grid API.
Just a minor thing to change, can you give a different name to x? what is x?
I know that it was already like that, but since you're changing that line, let's improve it!

2021-11-02 12:54 UTC, rugoncalves approved these changes
Approved! :)

2021-11-02 13:30 UTC, tmbp95 approved these changes

2021-11-03 09:57 UTC, JoaoFerreira-FrontEnd approved these changes

2021-11-04 09:53 UTC, merged