RGRIDT-1098: Triggering change data event on undo/redo of row insertion/deletion
OutSystems/outsystems-datagrid-reactive pull request #176
Opened 2021-12-21 15:59 UTC by glundgren93

This PR adds the necessary changes for the grid to trigger DataChange event on row insertion/deletion undo and redo.

### What was happening
* ![RGRIDT-1098](https://user-images.githubusercontent.com/3113318/146960070-85842c6b-2cb9-4df6-a6f1-a7f64f338898.gif)

### What was done
* Created GridRemoveRowAction in order to override wijmo's default undo/redo method of row deletion.
* Added event trigger on GridInsertRowAction and GridRemoveRowAction

Test Steps
1. Add row
2. Control z

Expected: “We couldn't find any data to show here” should appear.

1. Add row.
2. Delete row.
3. Control z

Expected: “We couldn't find any data to show here” should not be displayed

2021-12-21 16:48 UTC, JoaoFerreira-FrontEnd requested changes

2021-12-21 16:48 UTC, JoaoFerreira-FrontEnd commented on code/src/WijmoProvider/Features/Rows.ts
> +            const cv = grid.provider.itemsSource;
can we improve this var name?

2021-12-21 16:48 UTC, JoaoFerreira-FrontEnd commented on code/src/WijmoProvider/Features/Rows.ts
> +            const cv = grid.provider.itemsSource;
here too

2021-12-21 17:19 UTC, glundgren93 commented on code/src/WijmoProvider/Features/Rows.ts
> +            const cv = grid.provider.itemsSource;
done

2021-12-21 17:19 UTC, glundgren93 commented on code/src/WijmoProvider/Features/Rows.ts
> +            const cv = grid.provider.itemsSource;
done

2021-12-21 18:06 UTC, JoaoFerreira-FrontEnd approved these changes

2021-12-22 08:26 UTC, tmbp95 approved these changes

2021-12-22 10:08 UTC, merged