ROU-3067: Fixing issue where Add Row would throw error
OutSystems/outsystems-datagrid-reactive pull request #191
Opened 2022-02-02 17:02 UTC by glundgren93

This PR fixes a bug on Grids that are not using ArrangeData action to serialize data. Since the grid didn't have metadata, an error was thrown.

[Sample page](url)

### What was done
* If there is no metadata and there is data on our dataSource, retrieve items from the first item of dataSource.

### Test Steps
1. Open the context menu
2. Add a new row

Expected: New row should be added and it all columns should be working properly.

2022-02-02 17:44 UTC, joselrio approved these changes

2022-02-02 18:14 UTC, rugoncalves approved these changes

2022-02-03 09:11 UTC, rugoncalves requested changes

2022-02-03 09:11 UTC, rugoncalves commented on code/src/OSFramework/Grid/AbstractDataSource.ts
> +                    `Unable to add row. Please use ArrangeData action to serialize your data.`
Add this to the new Enum ErrorMessage.

2022-02-03 13:48 UTC, bmarcelino-fe submitted a review, later dismissed

2022-02-03 16:32 UTC, joanabpereira approved these changes

2022-02-03 16:33 UTC, rugoncalves approved these changes
Beautiful code! :)

2022-02-03 16:49 UTC, merged