ROU-4011: Fix parent dropdown not erasing the child when returning to its original value
OutSystems/outsystems-datagrid-reactive pull request #310
Opened 2022-12-20 10:53 UTC by OS-giulianasilva

This PR is for fix parent dropdown not erasing the child when returning to its original value

### What was happening
* The parent dropdown handler was not erasing the child value when oldValue === newValue

### What was done
* Removed the code that erases the dropdown child cell from the if that verifies if the oldValue is different than the newValue.
* Now it also erases the values when the oldValue is equal to the newValue.

### Test Steps
1. Go to the DropdownDependency test page 
2. Change the parent dropdown of the first row to different value
3. Change the child dropdown of the first row to a different value
4. Change the parent dropdown of the first row to the original value
5. Check if the child dropdown of the first row is empty, has a dirty mark and is invalid.

### Checklist
* [x] tested locally
* [x] documented the code
* [x] clean all warnings and errors of eslint
* [ ] requires changes in OutSystems (if so, provide a module with changes)
* [ ] requires new sample page in OutSystems (if so, provide a module with changes)

2022-12-20 15:15 UTC, JoaoFerreira-FrontEnd requested changes

2022-12-20 15:15 UTC, JoaoFerreira-FrontEnd commented on src/Providers/DataGrid/Wijmo/Columns/DropdownColumn.ts
> +                if (!existingEditActionForColRow) {
change it to (existingEditActionForColRow === false) please

2022-12-21 09:34 UTC, JoaoFerreira-FrontEnd approved these changes

2022-12-21 10:27 UTC, bmarcelino-fe approved these changes

2022-12-21 10:30 UTC, merged